apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  selector: # select pods to connect
    app: hello-world
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001 # containerport defined in deploment